### ISSUE TITLE
admin/view/template/extension/payment/liqpay

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#1]
Opencart 3.0.2.0 Fix for Liqpay
Find:

{% endif %}>
replace with:
{% endif %}

Thank you for taking then time in including more bug fixes, i did start a version myself. i have popped a link that i hope will help that include most 3020 fixes as well you yours upto date. from github and OC forum 
https://www.filehosting.org/file/details/804030/3.0.2.0-OpenCart-With-Fixes-upto-2june2019.zip

**Comment by condor2** [comment]
Tks for report
