### ISSUE TITLE
Change refresh icon to sync-alt 3.0.2.0 and Later

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#18]
upload/catalog/view/theme/default/template/checkout/cart.twig

FROM
`<button type="submit" data-toggle="tooltip" title="{{ button_update }}" class="btn btn-primary"><i class="fas fa-refresh"></i></button>`

TO
`<button type="submit" data-toggle="tooltip" title="{{ button_update }}" class="btn btn-primary"><i class="fas fa-sync-alt"></i></button>`

**Comment by condor2** [comment]
3.0.2.0 doesn't use Font Awesome 5.0

**Comment by waxedperfection** [comment]
Whoops sorry...
