### ISSUE TITLE
Success message is incorrect - 3.0.2.0 and Later

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#3]
OC contact form is working OK but the success message is incorrect. The message reads "You have been logged off your account. It is now safe to leave the computer. Your shopping cart has been saved, the items inside it will be restored whenever you log back into your account." 

Which appears to be the logout message? 

OC 3.0.2.0 and Later
FIX - catalog/view/theme/*****/template/common/success.twig 

See what code you have under 
`<h1>{{ heading_title }}</h1>`

This is a bug as default code is 
`{{ text_message }}`

It should be (around line 21)
`{{ text_success }}`

**Comment by condor2** [comment]
Added
