### ISSUE TITLE
Changes in SEO 3.0.2.0

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#36]
Noticed OC master had changes to the SEO

Daniel K reports "old system only worked for certain pages. info, prods, cats"

https://github.com/opencart/opencart/commit/0acc60959b8d820409483c7c2954695acb2eeca6

**Comment by condor2** [comment]
Is a lot of work to tweak 3.0.2.0 with master branch seo code. I will revert back

**Comment by waxedperfection** [comment]
Ok, No problem, im just happy to help as and when i can.
