### ISSUE TITLE
.o SQL in admin/model/sale/order.php 3.0.2.0 and Later

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#4]
**On line 391 there is an extra "o.":**
$sql .= " AND CONCAT(firstname, ' ', o.lastname) LIKE '%" . $this->db->escape($data['filter_customer']) . "%'";

It should be:
$sql .= " AND CONCAT(firstname, ' ', lastname) LIKE '%" . $this->db->escape($data['filter_customer']) . "%'";

**Comment by condor2** [comment]
Fixed. Tks
