### ISSUE TITLE
entry_option_points or entry_points? 3.0.2.0

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#49]
upload/admin/view/template/catalog/product_form.twig

`<td class="text-right">{{ entry_option_points }}</td>';`

`<td class="text-right">{{ entry_points }}</td>';`

https://github.com/opencart/opencart/commit/8fa956dd30b355f7e5c015e216b08e97e325c5c1

i see in a later version the latter was used. in 3.0.2.0 the first was used.

**Comment by condor2** [comment]
I think was a bug on master branch and they forgot to change the 3.0.2.0 code.
