### ISSUE TITLE
Styling fix for responsive devices 3.0.2.0

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#53]
Add to style sheet

@media (max-width: 767px) {
    input[name='search'] {
        margin-bottom: 15px;
    }
}

this will allow a botton margin as at the moment they are bunched together on search page in mobile and tablet view.

**Comment by condor2** [comment]
Screenshot?

**Comment by waxedperfection** [comment]
https://pasteboard.co/IqdJfkm.png

**Comment by condor2** [comment]
I think 5px is ok :)

**Comment by waxedperfection** [comment]
Sure I think it needs a little padding as it's very close together, could always go lucky7
