### ISSUE TITLE
Use of "index.php?route=product/manufacturer" 3.0.2.0

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#72]
catalog/view/theme/default/template/product/manufacturer_list.twig

NOW:
` &nbsp;&nbsp;&nbsp;<a href="index.php?route=product/manufacturer#{{ category.name }}">{{ category.name }}</a> {% endfor %} </p>`

Should be:
`&nbsp;&nbsp;&nbsp;<a href="{{ category.href }}#{{ category.name }}">{{ category.name }}</a> {% endfor %} </p>`

**Comment by condor2** [comment]
@waxedperfection you can fork this repo, I don't know if I will continue.

**Comment by waxedperfection** [comment]
@condor2 That would be a real shame, sadly i dont know enough to be able to continue from where you left off, if you can double check the "issues" that are open and update them before you close the repo, i will them just download the very last of the updates. but its a real shame. but thank you for your time and effort. WP

**Comment by condor2** [comment]
If you change to `<a href="{{ category.href }}#` when you will click on a manufacturer letter you will be redirected to home page and will not jump (anchor) to that letter.

**Comment by waxedperfection** [comment]
Correct - Closed Thankyou
