### ISSUE TITLE
col-xs-* have been dropped in Bootstrap 4 3.0.2.0

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#78]
catalog/view/javascript/common.js

Replace:
$('#content .row > .product-grid').attr('class', 'product-layout product-list col-xs-12');

With:
$('#content .row > .product-grid').attr('class', 'product-layout product-list col-12');

**Comment by condor2** [comment]
3.0.2.0 doesn't use Bootstrap 4
