### ISSUE TITLE
One More locations 3.0.2.0

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#81]
admin/view/template/localisation/location_list.twig

From
<td class="text-center">{% if locations.location_id in selected %}

To
<td class="text-center">{% if location.location_id in selected %}

Source: https://github.com/opencart/opencart/commit/ca579f5ebf9d68e772ebd9ec8317363d29ce86f6#diff-eecfc993bf74ceea2696d89fc7390446

**Comment by condor2** [comment]
I know
https://github.com/condor2/Opencart_3020/commit/22a8480dccce510d7c3e1105cc77ae5ae0e747b9
