### ISSUE TITLE
//--></script>

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#88]
catalog/view/theme/default/template/extension/module/banner.twig
catalog/view/theme/default/template/extension/module/carousel.twig
catalog/view/theme/default/template/extension/module/slideshow.twig
install/view/template/common/column_left.twig

Replace:
--></script>
With:
//--></script>

HTML comments  are no longer needed because the all modern browsers understand the <script> tag.

**Comment by condor2** [comment]
https://github.com/condor2/Opencart_3020/commit/c7bd495724698cff0700a72e42c23b5ada460ee3
