### ISSUE TITLE
Affliate Spelt wrong in a few places (Affiliate)

### ISSUE THREAD

**Issue by waxedperfection** [condor2/Opencart_3020#89]
upload/admin/language/en-gb/setting/setting.php
line 146 x two places

upload/admin/controller/customer/customer.php
line 822
line 1077

upload/admin/model/customer/customer.php
line 275

**Comment by condor2** [comment]
https://github.com/condor2/Opencart_3020/commit/c7bd495724698cff0700a72e42c23b5ada460ee3#diff-648d7671c6e4391448071d5f7c976208
